<script>
export default {}
</script>

<template>
  <nav class="navbar">
    <div class="flex items-center">
      <nuxt-link
        to="/"
        class="navbar-logo"
        exact-active-class="no-active-style"
      >
        <img
          class="navbar-logo-image"
          src="~/assets/bencodezen-logo.png"
          alt="BenCodeZen Dragon Logo"
        />
        BenCodeZen
      </nuxt-link>
    </div>
    <div>
      <nuxt-link to="/" class="navbar-item">Home</nuxt-link>
      <nuxt-link to="/blog" class="navbar-item">Blog</nuxt-link>
      <nuxt-link to="/learn" class="navbar-item">Learn</nuxt-link>
      <nuxt-link to="/about" class="navbar-item">About</nuxt-link>
      <nuxt-link to="/contact" class="navbar-item ">Contact</nuxt-link>
    </div>
  </nav>
</template>

<style lang="scss">
@import '../styles/_settings.scss';

.navbar {
  @apply flex justify-between items-center;
  @apply py-3 px-5;
  border-bottom: 2px solid #eaecef;
  color: #2c3e50;
  font-weight: 500;
  font-family: 'Poppins';
}

.navbar-item {
  @apply mr-5;
  font-size: 0.9rem;

  &:last-child {
    @apply mr-0;
  }

  &:hover {
    border-bottom: 2px solid $c-primary;
  }
}

.navbar-logo {
  @apply flex items-center;
  font-size: 1.3rem;
  font-weight: 600;
}

.navbar-logo-image {
  display: inline-block;
  width: 36px;
  @apply mr-3;
}

// Generated by Nuxt Router
.nuxt-link-exact-active {
  border-bottom: 2px solid $c-primary;
}
</style>
